#!/bin/bash

################################################################################
# prepare and start the interactive shell environment
################################################################################

# change to project directory
cd /src

# source doshie rc
DOSHIE_PROJECT_NAME=doshie

if [[ -f .doshie.rc ]]; then
  . .doshie.rc
fi

# set environment vars
cat <<! >/etc/profile.d/doshie.sh
export PATH="/src/.doshie/bin:$PATH"
export PS1="$DOSHIE_PROJECT_NAME> "
cd /src
!

chmod +x /etc/profile.d/doshie.sh
. /etc/profile.d/doshie.sh

cat .doshie/logo >&2

# update the environment
update

# create group to match host group
doshie_group="$( cat /etc/group | awk -F: '$3 == 1000 { print $1 }' )"

if [[ -z "$doshie_group" ]]; then
  echo "creating group doshie_grp_$DOSHIE_GID" >&2
  groupadd -g $DOSHIE_UID doshie_grp_$DOSHIE_GID
fi

# create user to match host user
if ! id -u "$DOSHIE_UID" >/dev/null 2>&1; then 
  echo "creating user doshie_$DOSHIE_UID" >&2
  useradd -u $DOSHIE_UID -g $DOSHIE_GID doshie_$DOSHIE_UID
  echo "doshie_$DOSHIE_UID    ALL = NOPASSWD: ALL" >> /etc/sudoers
fi

# mark the system as ready
touch .doshie/.ready

# start the interactive shell
if [[ -z "$DOSHIE_CMD" ]]; then
  su - doshie_$DOSHIE_UID
else
  # ..or run the command
  su - doshie_$DOSHIE_UID -c "$DOSHIE_CMD"
fi
