#!/bin/bash

################################################################################
# run some tests on doshie
################################################################################

set -x
set -e

test_dir="$( mktemp -d )"

# make a test project
cd $test_dir

# install doshie
mkdir ./.doshie
rsync -avr /home/travis/build/andyichr/doshie/ ./.doshie/
cp .doshie/shell ./

# run a shell command
./shell /bin/true

# run a second command
./shell echo "16b90581-53f2-430a-8b16-3a02b35e224b" | grep 16b90581-53f2-430a-8b16-3a02b35e224b

# remove the shell and verify it's gone
./shell --rm

# verify no containers exist
[[ "$( docker ps -a -q --no-trunc | wc -l )" == "0" ]]

# done
#echo "doshie was successfully verified" >&2
